source 'https://rubygems.org'
ruby '2.0.0'

gem 'rails', '4.1.1'
gem 'sass-rails', '~> 4.0.3'
gem 'coffee-rails', '~> 4.0.1'
gem 'uglifier', '>= 2.5.1'
gem 'jquery-rails'
gem 'jquery-cookie-rails'
gem 'turbolinks'
gem 'pg'
gem 'bootstrap-sass', '~> 3.1.1'
gem 'enumify'
gem 'controller_support'
gem 'haml'
gem 'omniauth'
gem 'omniauth-github'
gem 'octokit'
gem 'redcarpet'
gem 'rouge'
gem 'md_emoji'
gem 'hogan_assets'
gem 'compass-rails', '~> 1.1.7'
gem 'animation', '~> 0.1.alpha.3'
gem 'font-awesome-rails', '~> 4.1.0.0'
gem 'twitter-typeahead-rails'
gem 'active_model_serializers'
gem 'postmark-mitt', '0.0.8'
gem 'will_paginate-bootstrap'

group :production do
  gem 'rails_12factor'
end

group :development do
  gem 'quiet_assets'
  gem 'awesome_print'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'powder'
end
