default: &default
  adapter: postgresql
  encoding: unicode
  database: katalog_db
  host: localhost
  pool: 5

development:
  <<: *default
  database: katalog_local

test:
  <<: *default
  database: katalog_test

production:
  adapter: postgresql
  encoding: unicode
  database: katalog_production
  pool: 5